spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  redis:
    host: localhost
    port: 6379

websocket:
  host: 0.0.0.0
  port: 8888
  ping_timeout: 5000
  pint_interval: 2500
  upgrade_timeout: 10000
  boss_threads: 4
  worker_threads: 4
  use_linux_native_epoll: false